// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type IndiaCbfcRatings string

const (
	IndiaCbfcRatingsU  IndiaCbfcRatings = "U"
	IndiaCbfcRatingsUA IndiaCbfcRatings = "U/A"
	IndiaCbfcRatingsA  IndiaCbfcRatings = "A"
	IndiaCbfcRatingsS  IndiaCbfcRatings = "S"
)

func (e *IndiaCbfcRatings) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IndiaCbfcRatings(s)
	case string:
		*e = IndiaCbfcRatings(s)
	default:
		return fmt.Errorf("unsupported scan type for IndiaCbfcRatings: %T", src)
	}
	return nil
}

type NullIndiaCbfcRatings struct {
	IndiaCbfcRatings IndiaCbfcRatings
	Valid            bool // Valid is true if IndiaCbfcRatings is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIndiaCbfcRatings) Scan(value interface{}) error {
	if value == nil {
		ns.IndiaCbfcRatings, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IndiaCbfcRatings.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIndiaCbfcRatings) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IndiaCbfcRatings), nil
}

func (e IndiaCbfcRatings) Valid() bool {
	switch e {
	case IndiaCbfcRatingsU,
		IndiaCbfcRatingsUA,
		IndiaCbfcRatingsA,
		IndiaCbfcRatingsS:
		return true
	}
	return false
}

func AllIndiaCbfcRatingsValues() []IndiaCbfcRatings {
	return []IndiaCbfcRatings{
		IndiaCbfcRatingsU,
		IndiaCbfcRatingsUA,
		IndiaCbfcRatingsA,
		IndiaCbfcRatingsS,
	}
}

type MpaRatings string

const (
	MpaRatingsG    MpaRatings = "G"
	MpaRatingsPG   MpaRatings = "PG"
	MpaRatingsPG13 MpaRatings = "PG-13"
	MpaRatingsR    MpaRatings = "R"
	MpaRatingsNC17 MpaRatings = "NC-17"
)

func (e *MpaRatings) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MpaRatings(s)
	case string:
		*e = MpaRatings(s)
	default:
		return fmt.Errorf("unsupported scan type for MpaRatings: %T", src)
	}
	return nil
}

type NullMpaRatings struct {
	MpaRatings MpaRatings
	Valid      bool // Valid is true if MpaRatings is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMpaRatings) Scan(value interface{}) error {
	if value == nil {
		ns.MpaRatings, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MpaRatings.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMpaRatings) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MpaRatings), nil
}

func (e MpaRatings) Valid() bool {
	switch e {
	case MpaRatingsG,
		MpaRatingsPG,
		MpaRatingsPG13,
		MpaRatingsR,
		MpaRatingsNC17:
		return true
	}
	return false
}

func AllMpaRatingsValues() []MpaRatings {
	return []MpaRatings{
		MpaRatingsG,
		MpaRatingsPG,
		MpaRatingsPG13,
		MpaRatingsR,
		MpaRatingsNC17,
	}
}

type Roles string

const (
	RolesRegularUser Roles = "regular_user"
	RolesAdmin       Roles = "admin"
)

func (e *Roles) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Roles(s)
	case string:
		*e = Roles(s)
	default:
		return fmt.Errorf("unsupported scan type for Roles: %T", src)
	}
	return nil
}

type NullRoles struct {
	Roles Roles
	Valid bool // Valid is true if Roles is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoles) Scan(value interface{}) error {
	if value == nil {
		ns.Roles, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Roles.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoles) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Roles), nil
}

func (e Roles) Valid() bool {
	switch e {
	case RolesRegularUser,
		RolesAdmin:
		return true
	}
	return false
}

func AllRolesValues() []Roles {
	return []Roles{
		RolesRegularUser,
		RolesAdmin,
	}
}

type City struct {
	ID          string
	CreatedAt   pgtype.Timestamptz
	DisplayName string
	State       string
	Coordinates string
}

type LoginToken struct {
	Token         string
	Version       int32
	CreatedAt     pgtype.Timestamptz
	UserID        int64
	Otp           string
	ExpireAt      pgtype.Timestamptz
	LastAttemptAt pgtype.Timestamptz
	TotalAttempts int32
}

type Movie struct {
	ID                         int64
	CreatedAt                  pgtype.Timestamptz
	Version                    int32
	Title                      string
	Slug                       string
	Poster                     string
	RunningDurationInMinutes   int32
	AvailableAudioLanguages    []string
	AvailableSubtitleLanguages []string
	AvailableFormats           []string
	Rating                     string
	TotalRatingCount           int32
	Genres                     []string
	ReleaseDate                pgtype.Date
	IsInCinema                 bool
	IndiaCbfcRating            IndiaCbfcRatings
	MpaRating                  MpaRatings
	About                      string
	ImdbID                     string
	ImdbRating                 string
	ImdbLastSyncedAt           pgtype.Timestamptz
}

type MovieGenre struct {
	ID          string
	CreatedAt   pgtype.Timestamptz
	DisplayName string
	About       string
}

type MoviesCast struct {
	MovieID        int64
	MoviesPersonID int64
	Index          int32
}

type MoviesCrew struct {
	MovieID        int64
	MoviesPersonID int64
	Index          int32
}

type MoviesFormat struct {
	ID        string
	CreatedAt pgtype.Timestamptz
	About     string
}

type MoviesLanguage struct {
	ID          string
	CreatedAt   pgtype.Timestamptz
	DisplayName string
	EnglishName string
}

type MoviesPerson struct {
	ID               int64
	CreatedAt        pgtype.Timestamptz
	Version          int32
	Name             string
	Slug             string
	Nicknames        []string
	ProfilePicture   string
	Occupations      []string
	Dob              pgtype.Date
	About            string
	ImdbID           string
	ImdbLastSyncedAt pgtype.Timestamptz
}

type MoviesReview struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Version   int32
	MovieID   int64
	AuthorID  int64
	Text      string
	Rating    int32
}

type MoviesVideo struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	Version     int32
	MovieID     int64
	Language    string
	YoutubeLink string
	Index       int32
}

type RefreshToken struct {
	ID        int64
	Token     string
	CreatedAt pgtype.Timestamptz
	UserID    int64
	UserRole  Roles
	ExpireAt  pgtype.Timestamptz
	UserAgent string
}

type User struct {
	ID                   int64
	CreatedAt            pgtype.Timestamptz
	Version              int32
	Name                 string
	Email                string
	Role                 Roles
	Dob                  pgtype.Date
	LastLoginTokenSentAt pgtype.Timestamptz
	TotalLoginTokensSent int32
}
