// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: movies_persons.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMoviesPerson = `-- name: CreateMoviesPerson :one
INSERT INTO
    "movies_persons" (
        "name",
        "slug",
        "nicknames",
        "profile_picture",
        "occupations",
        "dob",
        "about",
        "imdb_id",
        "imdb_last_synced_at"
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
    "id"
`

type CreateMoviesPersonParams struct {
	Name             string
	Slug             string
	Nicknames        []string
	ProfilePicture   string
	Occupations      []string
	Dob              pgtype.Date
	About            string
	ImdbID           string
	ImdbLastSyncedAt pgtype.Timestamptz
}

func (q *Queries) CreateMoviesPerson(ctx context.Context, arg *CreateMoviesPersonParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMoviesPerson,
		arg.Name,
		arg.Slug,
		arg.Nicknames,
		arg.ProfilePicture,
		arg.Occupations,
		arg.Dob,
		arg.About,
		arg.ImdbID,
		arg.ImdbLastSyncedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
