// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: movies_languages.sql

package database

import (
	"context"
)

const checkIfAnyMoviesAvailableAudioLanguagesExist = `-- name: CheckIfAnyMoviesAvailableAudioLanguagesExist :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            "movies_available_audio_languages"
        WHERE
            "movies_language_id" = $1
    )
`

func (q *Queries) CheckIfAnyMoviesAvailableAudioLanguagesExist(ctx context.Context, moviesLanguageID int64) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfAnyMoviesAvailableAudioLanguagesExist, moviesLanguageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkIfAnyMoviesAvailableSubtitleLanguagesExist = `-- name: CheckIfAnyMoviesAvailableSubtitleLanguagesExist :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            "movies_available_subtitle_languages"
        WHERE
            "movies_language_id" = $1
    )
`

func (q *Queries) CheckIfAnyMoviesAvailableSubtitleLanguagesExist(ctx context.Context, moviesLanguageID int64) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfAnyMoviesAvailableSubtitleLanguagesExist, moviesLanguageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createMoviesLanguage = `-- name: CreateMoviesLanguage :one
INSERT INTO
    "movies_languages" ("slug", "display_name", "english_name")
VALUES
    ($1, $2, $3)
RETURNING
    id, created_at, version, display_name, english_name, slug
`

type CreateMoviesLanguageParams struct {
	Slug        string
	DisplayName string
	EnglishName string
}

func (q *Queries) CreateMoviesLanguage(ctx context.Context, arg *CreateMoviesLanguageParams) (MoviesLanguage, error) {
	row := q.db.QueryRow(ctx, createMoviesLanguage, arg.Slug, arg.DisplayName, arg.EnglishName)
	var i MoviesLanguage
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Version,
		&i.DisplayName,
		&i.EnglishName,
		&i.Slug,
	)
	return i, err
}

const deleteMoviesLanguage = `-- name: DeleteMoviesLanguage :exec
DELETE FROM "movies_languages"
WHERE
    id = $1
`

func (q *Queries) DeleteMoviesLanguage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMoviesLanguage, id)
	return err
}

const getAllMoviesLanguages = `-- name: GetAllMoviesLanguages :many
SELECT
    id, created_at, version, display_name, english_name, slug
FROM
    "movies_languages"
`

func (q *Queries) GetAllMoviesLanguages(ctx context.Context) ([]MoviesLanguage, error) {
	rows, err := q.db.Query(ctx, getAllMoviesLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MoviesLanguage
	for rows.Next() {
		var i MoviesLanguage
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Version,
			&i.DisplayName,
			&i.EnglishName,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMoviesLanguageByID = `-- name: GetMoviesLanguageByID :one
SELECT
    id, created_at, version, display_name, english_name, slug
FROM
    "movies_languages"
WHERE
    "id" = $1
`

func (q *Queries) GetMoviesLanguageByID(ctx context.Context, id int64) (MoviesLanguage, error) {
	row := q.db.QueryRow(ctx, getMoviesLanguageByID, id)
	var i MoviesLanguage
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Version,
		&i.DisplayName,
		&i.EnglishName,
		&i.Slug,
	)
	return i, err
}

const updateMoviesLanguage = `-- name: UpdateMoviesLanguage :exec
UPDATE "movies_languages"
SET
    "slug" = $1,
    "display_name" = $2,
    "english_name" = $3,
    "version" = "version" + 1
WHERE
    "id" = $4
    AND "version" = $5
`

type UpdateMoviesLanguageParams struct {
	Slug        string
	DisplayName string
	EnglishName string
	ID          int64
	Version     int32
}

func (q *Queries) UpdateMoviesLanguage(ctx context.Context, arg *UpdateMoviesLanguageParams) error {
	_, err := q.db.Exec(ctx, updateMoviesLanguage,
		arg.Slug,
		arg.DisplayName,
		arg.EnglishName,
		arg.ID,
		arg.Version,
	)
	return err
}
