// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: refresh_tokens.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO
    "refresh_tokens" ("created_at", "user_id", "user_role", "expire_at", "user_agent")
VALUES
    ($1, $2, $3, $4, $5)
RETURNING
    "id",
    "created_at",
    "user_id",
    "user_role",
    "expire_at",
    "user_agent"
`

type CreateRefreshTokenParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserID    int64              `json:"user_id"`
	UserRole  Roles              `json:"user_role"`
	ExpireAt  pgtype.Timestamptz `json:"expire_at"`
	UserAgent string             `json:"user_agent"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg *CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.CreatedAt,
		arg.UserID,
		arg.UserRole,
		arg.ExpireAt,
		arg.UserAgent,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.UserRole,
		&i.ExpireAt,
		&i.UserAgent,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM "refresh_tokens"
WHERE
    id = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, id)
	return err
}

const findRefreshToken = `-- name: FindRefreshToken :one
SELECT
    "id",
    "created_at",
    "user_id",
    "user_role",
    "expire_at",
    "user_agent"
FROM
    "refresh_tokens"
WHERE
    id = $1
`

func (q *Queries) FindRefreshToken(ctx context.Context, id int64) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, findRefreshToken, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.UserRole,
		&i.ExpireAt,
		&i.UserAgent,
	)
	return i, err
}
